api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
        jsonapi: ['application/vnd.api+json']
    swagger:
        versions: [3]
    # formats:
    #     json:     ['application/json']
    #     jsonld:   ['application/ld+json']
    #     jsonhal:  ['application/hal+json']
    #     jsonapi:  ['application/vnd.api+json']